### PR TITLE
Copy runtimeoptions from project.json to runtimeconfig.json

### PR DESCRIPTION
**Pull request by livarcocc**
Moved ProjectModel to json.net for GlobalSettings and Project.json. Kept LockFileReader using the old API as I don't have the cycles to add the tests for it at the moment.

Added unit tests covering parsing of Json for all the pieces of the project.json

Added a RawRuntimeOptions to Project and made Executable deserialize that into the runtimeOptions of runtimeconfig.json

Added tests to cover copying runtimeoptions during dotnet build.

cc @davidfowl @anurse @piotrpMSFT @brthor @gkhanna79 @schellap

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2227)

### CODE REVIEW

**Comment by weshaggard** [comment]
I'm seeing a number of failed builds, see http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_windows_nt_x64_prtest/781/consoleFull

```
00:40:48 D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\stage2\dotnet.exe compile-csc @D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\obj\Debug\netstandardapp1.5\dotnet-compile.rsp returned Exit Code 1
00:40:48 D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\Program.cs(12,18): error CS1002: ; expected
00:40:48 D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\Program.cs(12,27): error CS1002: ; expected
00:40:48 D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\Program.cs(12,34): error CS1002: ; expected
00:40:48 D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\Program.cs(12,35): error CS1525: Invalid expression term '}'
00:40:48 D:\j\workspace\release_windo---4c3b899b\test\dotnet-publish.Tests\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\bin\Release\netstandardapp1.5\win7-x64\CompilationFailedTest\CompileFail\Program.cs(12,35): error CS1002: ; expected
00:40:48 Compilation failed.
00:40:48     0 Warning(s)
00:40:48     5 Error(s)
```

Yet the CI is reporting success. Is there some errors not correctly propagating?

**Comment by schellap** [comment]
CompilationFailedTest. So tests bad program compilation.

**Comment by livarcocc** [comment]
@weshaggard Yep, that is expected, it is a test that we fail when trying to compile a bad project.

File: src/Microsoft.DotNet.ProjectModel/FileFormatException.cs [hunk 1]
```diff
@@ -29,20 +31,11 @@ public override string ToString()
 
         internal static FileFormatException Create(Exception exception, string filePath)
         {
-            if (exception is JsonDeserializerException)
```
Comment (davidfowl) [inline src/Microsoft.DotNet.ProjectModel/FileFormatException.cs]: This looks like you'll lose some information. I believe there's an equivalent thing you can cast to for the JSON.NET specific exception.

**Comment by davidfowl** [comment]
Might be worth comparing the JSON.NET conversion to this code https://github.com/aspnet/dnx/blob/1.0.0-beta4/src/Microsoft.Framework.Runtime/Project.cs. We used JSON.NET a while ago but most of the project parsing is the same.

File: src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs [hunk 2]
```diff
@@ -26,18 +32,16 @@ public PackIncludeEntry(string target, string[] sourceGlobs, int line, int colum
             Column = column;
         }
 
-        private static string[] ExtractValues(JsonValue json)
+        private static string[] ExtractValues(JToken json)
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs]: This seems like a converter method. `JTokenConverter.ToStringArray(JToken json)`?

File: src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs [hunk 3]
```diff
@@ -13,9 +14,14 @@ public class PackIncludeEntry
...
         public int Column { get; }
 
-        internal PackIncludeEntry(string target, JsonValue json)
-            : this(target, ExtractValues(json), json.Line, json.Column)
+        internal PackIncludeEntry(string target, JToken json)
         {
+            Target = target;
+            SourceGlobs = ExtractValues(json);
+
+            var lineInfo = (IJsonLineInfo)json;
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs]: A character address type would be convenient to have at some point

File: src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs [hunk 4]
```diff
@@ -79,13 +79,16 @@ internal void EnsureInitialized()
...
-                    .Keys
-                    .Select(k => new PackIncludeEntry(k, packIncludeJson.Value(k)))
-                    .ToList();
+                var packIncludeEntries = new List<PackIncludeEntry>();
+                foreach (var token in packIncludeJson)
+                {
+                    packIncludeEntries.Add(new PackIncludeEntry(token.Key, token.Value));
+                }
+
+                _packInclude = packIncludeEntries;
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs]: I prefer the original Linq-based syntax. A single statement is easier to maintain, IMO.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs [hunk 5]
```diff
@@ -73,6 +58,41 @@ public static bool TryGetGlobalSettings(string path, out GlobalSettings globalSe
             return true;
         }
 
+        public static GlobalSettings GetGlobalSettings(Stream fs, string globalJsonPath)
+        {
+            var globalSettings = new GlobalSettings();
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: This method has a bunch of responsibilities.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs [hunk 6]
```diff
@@ -73,6 +58,41 @@ public static bool TryGetGlobalSettings(string path, out GlobalSettings globalSe
...
+            }
+            catch (JsonReaderException)
+            {
+                throw new InvalidOperationException("The JSON file can't be deserialized to a JSON object.");
+            }
+
+            var projectSearchPaths = new string[] { };
+            JToken projectSearchPathsToken;
+            if (jobject.TryGetValue("projects", out projectSearchPathsToken) &&
+                projectSearchPathsToken.Type == JTokenType.Array)
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: This seems inconsistent with PackIncludeEntry. In PIE we consider a string value to be an array with one element. Here we only consider properties whose values use array syntax. Should we make this converter more permissive and unify our story?

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs [hunk 7]
```diff
@@ -73,6 +58,41 @@ public static bool TryGetGlobalSettings(string path, out GlobalSettings globalSe
...
+            {
+                projectSearchPaths = projectSearchPathsToken.ToObject<string[]>();
+            }
+            else if (jobject.TryGetValue("sources", out projectSearchPathsToken) &&
+                     projectSearchPathsToken.Type == JTokenType.Array)
+            {
+                projectSearchPaths = projectSearchPathsToken.ToObject<string[]>();
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: Same here.

File: src/Microsoft.DotNet.ProjectModel/ProjectReader.cs [hunk 8]
```diff
@@ -8,9 +8,10 @@
 using Microsoft.DotNet.ProjectModel.Files;
 using Microsoft.DotNet.ProjectModel.Graph;
 using Microsoft.DotNet.ProjectModel.Utilities;
-using Microsoft.Extensions.JsonParser.Sources;
+using Newtonsoft.Json;
 using NuGet.Frameworks;
 using NuGet.Versioning;
+using Newtonsoft.Json.Linq;
```
Comment (piotrpMSFT) [inline src/Microsoft.DotNet.ProjectModel/ProjectReader.cs]: Ordering nit :p :abc:

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+using Microsoft.DotNet.ProjectModel;
+using Newtonsoft.Json;
+using Newtonsoft.Json.Linq;
+using Xunit;
+using System.Linq;
+using FluentAssertions;
+
+namespace Microsoft.DotNet.ProjectModel.Tests
+{
+    public class GivenThatIWantToFilesMatchedWithPatternsInJson
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: What does it mean to Want To Files Matched?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+            var json = new JObject();
+            var project = GetProject(json);
+
+            project.Files.PackInclude.Should().BeEmpty();
+        }
+
+        [Fact]
+        public void It_sets_PackInclude_when_packInclude_is_set_in_the_ProjectJson()
+        {
+            const string somePackTarget = "some pack target";
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: We need moar TestInputGenerators [once we have a bit more time]

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+            var json = new JObject();
+            json.Add("excludeBuiltIn", "*.fs");
+            json.Add("exclude", "bin/");
+            json.Add("contentBuiltIn", "*.jpg");
+            json.Add("compileBuiltIn", "*.cs");
+            json.Add("resourceBuiltIn", "*.resx");
+            json.Add("publishExclude", "*.pdb");
+            Action action = () => GetProject(json);
+
+            action.ShouldNotThrow();
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: This test should pass for arbitrary keys & values, right? It's not clear this test adds value...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+            json.Add("resourceBuiltIn", "*.resx");
+            json.Add("publishExclude", "*.pdb");
+            json.Add("shared", "*.bin");
+            json.Add("resource", "../../**/*.resx");
+            json.Add("preprocess", "*.cs");
+            json.Add("compile", "*");
+            json.Add("content", "*.jpge");
+            Action action = () => GetProject(json);
+
+            action.ShouldNotThrow();
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: I'm not clear on the purpose of this one either. Should we at least be validating that these properties are being recognized and mapped onto the output of GetProject?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+        }
+
+        [Fact]
+        public void It_parses_namedResources_successfully()
+        {
+            var json = new JObject();
+            var namedResources= new JObject();
+            json.Add("namedResource", namedResources);
+
+            namedResources.Add("System.Strings", "System/Strings.resx");
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: Is this intentionally similar to System.String? Otherwise, a more obviously random string would be nice

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+
+            var project = GetProject(json);
+
+            project.Files.ResourceFiles.Keys.Should().Contain(
+                Path.GetFullPath(Path.Combine(Path.GetDirectoryName(ProjectFilePath), "System", "Strings.resx")));
+            project.Files.ResourceFiles.Values.Should().Contain("System.Strings");
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: Should we be validating the key/value mapping?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+        }
+
+        public Project GetProject(JObject json, ProjectReaderSettings settings = null)
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToFilesMatchedWithPatternsInJson.cs]: private?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 16]
```diff
@@ -0,0 +1,866 @@
...
+        private const string Version = "1.0.0";
+        private readonly string ProjectFilePath = AppContext.BaseDirectory;
+
+        private Project _emptyProject;
+        private readonly string[] _someDefines = new[] {"DEFINE1", "DEFINE2"};
+        private readonly string[] _noWarnings = new[] {"warn1", "warn2"};
+        private readonly string[] _someAdditionalArguments = new[] {"additional argument 1", "additional argument 2"};
+        private readonly VersionRange _versionRange = VersionRange.Parse(Version);
+        private readonly JObject _jsonCompilationOptions;
+        private CommonCompilerOptions commonCompilerOptions;
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: _commonCompilerOptions

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 17]
```diff
@@ -0,0 +1,866 @@
...
+            var json = new JObject();
+            Action action = () => GetProject(json);
+
+            action.ShouldNotThrow<Exception>();
+        }
+
+        [Fact]
+        public void It_sets_Name_to_the_passed_ProjectName_if_one_is_not_set_in_the_ProjectJson()
+        {
+            _emptyProject.Name.Should().Be(ProjectName);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: can the test better express the intent of this behavior? My expectation was that the ProjectName came from the project file's parent directory name... Instead it is being passed in externally?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 18]
```diff
@@ -0,0 +1,866 @@
...
+        }
+
+        [Fact]
+        public void It_sets_Name_to_the_Name_in_the_ProjectJson_when_one_is_set()
+        {
+            const string nameInprojectJson = "some name in the project.json";
+            var json = new JObject();
+            json.Add("name", nameInprojectJson);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: nameInProjectJson

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 19]
```diff
@@ -0,0 +1,866 @@
...
+        }
+
+        [Fact]
+        public void It_sets_the_project_file_path()
+        {
+            _emptyProject.ProjectFilePath.Should().Be(ProjectFilePath);
+        }
+
+        [Fact]
+        public void It_sets_the_version_to_one_when_it_is_not_set()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: This is a huge test class. Should we make two, one for defaults and one for overrides?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 20]
```diff
@@ -0,0 +1,866 @@
...
+        {
+            var json = new JObject();
+            json.Add("version", "1.1");
+            var project = GetProject(json);
+
+            project.Version.Should().Be(new NuGetVersion("1.1"));
+        }
+
+        [Fact]
+        public void It_sets_AssemblyFileVersion_to_the_ProjectJson_version_when_AssemblyFileVersion_is_no_passed_in_the_settings()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: `not`_passed_in...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 21]
```diff
@@ -0,0 +1,866 @@
...
+        {
+            var json = new JObject();
+            json.Add("version", "1.1");
+            var project = GetProject(json);
+
+            project.AssemblyFileVersion.Should().Be(new NuGetVersion("1.1").Version);
+        }
+
+        [Fact]
+        public void It_sets_AssemblyFileVersion_Revision_to_the_AssemblyFileVersion_passed_in_the_settings_and_everything_else_to_the_projectJson_Version()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Whoa, really? So the AssemblyFileVersion is really the AssemblyFileRevision?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 22]
```diff
@@ -0,0 +1,866 @@
...
+            json.Add("version", "1.1");
+            var project = GetProject(json, new ProjectReaderSettings { AssemblyFileVersion = revision.ToString() });
+
+            var version = new NuGetVersion("1.1").Version;
+            project.AssemblyFileVersion.Should().Be(
+                new Version(version.Major, version.Minor, version.Build, revision));
+        }
+
+        [Fact]
+        public void It_throws_a_FormatException_when_AssemblyFileVersion_passed_in_the_settings_is_invalid()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: We should have a test for AssemblyFileVersion being a dot-seperated version number. I expect this will be common. Perhaps also a NuGet-style SemVer?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 23]
```diff
@@ -0,0 +1,866 @@
...
+        public void It_sets_requireLicenseAcceptance_to_false_when_one_is_not_set_in_the_ProjectJson()
+        {
+            _emptyProject.RequireLicenseAcceptance.Should().BeFalse();
+        }
+
+        [Fact]
+        public void It_sets_requireLicenseAcceptance_to_the_one_in_the_ProjectJson()
+        {
+            var json = new JObject();
+            json.Add("requireLicenseAcceptance", true);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: test name is a bit misleading. All this proves is that the value is true when a value is set in the Json...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 24]
```diff
@@ -0,0 +1,866 @@
...
+        public void It_sets_embedInteropTypes_to_false_when_one_is_not_set_in_the_ProjectJson()
+        {
+            _emptyProject.EmbedInteropTypes.Should().BeFalse();
+        }
+
+        [Fact]
+        public void It_sets_embedInteropTypes_to_the_one_in_the_ProjectJson()
+        {
+            var json = new JObject();
+            json.Add("embedInteropTypes", true);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: And here. Any.Boolean() would be handy here!

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 25]
```diff
@@ -0,0 +1,866 @@
...
+        }
+
+        [Fact]
+        public void It_does_not_add_commands_when_commands_is_not_set_in_the_ProjectJson()
+        {
+            _emptyProject.Commands.Should().BeEmpty();
+        }
+
+        [Fact]
+        public void It_does_not_add_commands_when_commands_is_not_a_JsonObject()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Commands should not be supported any longer. This is a remnant of DNX

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 26]
```diff
@@ -0,0 +1,866 @@
...
+        {
+            var json = new JObject();
+            json.Add("commands", true);
+            var project = GetProject(json);
+
+            project.Commands.Should().BeEmpty();
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Really? This should be malformatted json and throw some exception, no?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 27]
```diff
@@ -0,0 +1,866 @@
...
+            json.Add("commands", commands);
+
+            commands.Add("commandKey1", "commandValue1");
+            commands.Add("commandKey2", true);
+
+            var project = GetProject(json);
+
+            project.Commands.Count.Should().Be(1);
+            project.Commands.First().Key.Should().Be("commandKey1");
+            project.Commands.First().Value.Should().Be("commandValue1");
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Same here. Why are we accepting invalid input for a known property?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 28]
```diff
@@ -0,0 +1,866 @@
...
+        }
+
+        [Fact]
+        public void It_does_not_add_scripts_when_scripts_is_not_a_JsonObject()
+        {
+            var json = new JObject();
+            json.Add("scripts", true);
+            var project = GetProject(json);
+
+            project.Scripts.Should().BeEmpty();
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Same here

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 29]
```diff
@@ -0,0 +1,866 @@
...
+
+            scripts.Add("scriptKey1", "scriptValue1");
+            scripts.Add("scriptKey3", new JArray(scriptArrayValues));
+
+            var project = GetProject(json);
+
+            project.Scripts.Count.Should().Be(2);
+            project.Scripts.First().Key.Should().Be("scriptKey1");
+            project.Scripts.First().Value.Should().Contain("scriptValue1");
+            project.Scripts["scriptKey3"].Should().Contain(scriptArrayValues);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Same here

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 30]
```diff
@@ -0,0 +1,866 @@
...
+            var json = new JObject();
+            var scripts = new JObject();
+            json.Add("scripts", scripts);
+
+            scripts.Add("scriptKey2", true);
+
+            Action action = () => GetProject(json);
+
+            action.ShouldThrow<FileFormatException>()
+                .WithMessage("The value of a script in project.json can only be a string or an array of strings");
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: This is inline with comments above. Why are we accepting invalid input in some scenarios but throwing in others?

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 31]
```diff
@@ -0,0 +1,866 @@
...
+            compilationOptions.Add("analyzerOptions", analyzerOptions);
+
+            analyzerOptions.Add("languageId", "C#");
+
+            var project = GetProject(json);
+            project.AnalyzerOptions.LanguageId.Should().Be("C#");
+        }
+
+        [Fact]
+        public void It_throws_when_the_analyzerOptions_languageId_is_no_a_string()
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: _is_not_a...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 32]
```diff
@@ -0,0 +1,866 @@
...
+        {
+            var json = new JObject();
+            var compilationOptions = new JObject();
+            json.Add("compilationOptions", compilationOptions);
+
+            var analyzerOptions = new JObject();
+            compilationOptions.Add("analyzerOptions", analyzerOptions);
+
+            analyzerOptions.Add("languageId", true);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: We need a better model here, eventually. We only prove that booleans don't work at the moment...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 33]
```diff
@@ -0,0 +1,866 @@
...
+            configurations.Add("some configuration", someConfiguration);
+            var someConfigurationCompilationOptions = new JObject();
+            someConfiguration.Add("compilationOptions", someConfigurationCompilationOptions);
+            someConfigurationCompilationOptions.Add("allowUnsafe", false);
+
+            var project = GetProject(json);
+
+            commonCompilerOptions.AllowUnsafe = false;
+
+            project.GetCompilerOptions(null, "some configuration").Should().Be(commonCompilerOptions);
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: This test could use some attention. Teasing out the intent is not too easy...

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs [hunk 34]
```diff
@@ -0,0 +1,866 @@
...
+            var json = new JObject();
+            json.Add("dependencies", dependencies);
+
+            var project = GetProject(json);
+
+            var dependency = project.Dependencies.First();
+            dependency.Target.Should().Be(LibraryType.Project);
+        }
+        //+++++
+
```
Comment (piotrpMSFT) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: bad merge/

**Comment by piotrpMSFT** [comment]
wow, this adds significant missing coverage. The PR shows a number of inconsistencies in our implementation of projectmodel, but this is not the pr for fixing those.

:shipit:

File: src/Microsoft.DotNet.ProjectModel/FileFormatException.cs (hunk 1 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/FileFormatException.cs]: Added it back and added one for the Json.Net exception.

File: src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs (hunk 2 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/Files/PackIncludeEntry.cs]: I tried to refactor as little as possible. This was a big enough change without that already. A whole set of improvements could and should be made here, specially now that we have test coverage. But I don't want to do that as part of this change, as it would take more time and asp.net is blocked waiting for this change.

**Comment by anurse** [comment]
Nice! Love the improved test coverage, it's been in dire need of it for a while now. :shipit:

File: src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs (hunk 4 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs]: Easier said than done. We would need to add a bunch of dependencies to be able to do the select on the JObject directly. I preferred not to do that.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 5 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: Yes. Again, refactoring as little as possible for now.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 6 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: Yes, we should consider that. File an issue. I don't want to change this now.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 7 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: Same answer.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 17 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: That's the current behavior. Again, I am not altering behavior, just moving the code to use json.net.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 21 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Yep. Current behavior.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 22 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: I am just testing the json pieces.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 26 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: It is not malformed, it is simply something like "commands": true.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 25 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Agreed, but again, don't want to change behavior with this PR.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 27 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Existing behavior. And it is invalid in our semantics, but valid json.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 28 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Same answer.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 29 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Oops.

File: test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs (hunk 30 above)
Comment (livarcocc) [inline test/Microsoft.DotNet.ProjectModel.Tests/GivenThatIWantToLoadAProjectJsonFile.cs]: Same answer. Existing behavior.

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build please.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 7 above)
Comment (davidfowl) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: ToObject is hella slow, this is going to regress performance...

File: src/Microsoft.DotNet.Compiler.Common/Executable.cs [hunk 35]
```diff
@@ -131,31 +131,8 @@ private void WriteRuntimeConfig(LibraryExporter exporter)
...
-                    }
-                    else
-                    {
-                        var framework = new JObject(
-                            new JProperty("name", redistExport.Library.Identity.Name),
-                            new JProperty("version", redistExport.Library.Identity.Version.ToNormalizedString()));
-                        runtimeOptions.Add("framework", framework);
-                    }
-                }
+                WriteFramework(runtimeOptions, exporter);
```
Comment (brthor) [inline src/Microsoft.DotNet.Compiler.Common/Executable.cs]: :smile:

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 7 above)
Comment (livarcocc) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: Converted to Values<string>

**Comment by livarcocc** [comment]
Fixes https://github.com/dotnet/cli/issues/2121.

File: src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs (hunk 7 above)
Comment (JamesNK) [inline src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs]: ToObject for primitive values (string, int, etc) is fast but for complex objects like an array it will call the serializer.

**Comment by JamesNK** [comment]
Hi. I just want to double check that this won't lock the version of json.net that .NET CLI is using like it use to with DNX.

**Comment by anurse** [comment]
@JamesNK No, the CLI is a fully independent app that produces a complete compiled output for your app (think `msbuild`, :trollface:), whereas DNX was hosting your app in-process. The resulting application references whatever version of JSON.NET it wants.

**Comment by JamesNK** [comment]
:+1:
