### ISSUE TITLE
Run build.sh on branch `v2.1.3` doesn't work on Linux

### ISSUE THREAD

**Issue by dgodd** [dotnet/cli#8250]
## Steps to reproduce
```
docker run  -it microsoft/dotnet bash

git clone https://github.com/dotnet/cli
cd cli/
git checkout v2.1.3
export DropSuffix=true
./build.sh /t:Compile
```

## Expected  behavior
A built binary

## Actual behavior
Receives a 404 while downloading dotnet sdk, and does not recover. (Does not fallback to a new url)

```

dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
root@71cb5e91573c:/cli# 
```

## Environment data
Version of docker image: aeb50eb9b533

`dotnet --info` output:

```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

**Comment by livarcocc** [comment]
@johnbeisner can you take a look since this seems like a install script bug?

**Comment by johnbeisner** [comment]
@dgodd
Installations of 1.0.* versions of the SDK are not supported on Debian 9; therefore, builds of CLI v2.1.3 are not going to work on Debian 9. You should try to build this on Debian 8.

**Comment by dgodd** [comment]
Having switched to using jessie, `docker run  -it microsoft/dotnet:2-sdk-jessie bash` and then exactly the same setup. The build still fails with
```

Build FAILED.

       "/cli/build.proj" (Compile target) (1) ->
       (RestoreSrcPackages target) -> 
         /cli/src/dotnet/dotnet.csproj : warning NU1701: Package 'Microsoft.ApplicationInsights 2.0.0' was restored using '.NETPlatform,Version=v5.4, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/cli/build.proj]


       "/cli/build.proj" (Compile target) (1) ->
         /cli/src/dotnet/dotnet.csproj : warning NU1701: Package 'Microsoft.ApplicationInsights 2.0.0' was restored using '.NETPlatform,Version=v5.4, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/cli/src/redist/redist.csproj] [/cli/build.proj]
         /cli/src/redist/redist.csproj : warning NU1701: Package 'Microsoft.ApplicationInsights 2.0.0' was restored using '.NETPlatform,Version=v5.4, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/cli/build.proj]


       "/cli/build.proj" (Compile target) (1) ->
       "/cli/src/redist/redist.csproj" (Publish target) (2) ->
       (ReportAssetsLogMessages target) -> 
         /cli/src/redist/redist.csproj : warning NU1701: Package 'Microsoft.ApplicationInsights 2.0.0' was restored using '.NETPlatform,Version=v5.4, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.


       "/cli/build.proj" (Compile target) (1) ->
       "/cli/src/redist/redist.csproj" (Publish target) (2) ->
       "/cli/src/dotnet/dotnet.csproj" (default target) (3:2) ->
         /cli/src/dotnet/dotnet.csproj : warning NU1701: Package 'Microsoft.ApplicationInsights 2.0.0' was restored using '.NETPlatform,Version=v5.4, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.


       "/cli/build.proj" (Compile target) (1) ->
       "/cli/src/redist/redist.csproj" (Publish target) (2) ->
       "/cli/src/dotnet/dotnet.csproj" (default target) (3:2) ->
       (CoreCompile target) -> 
         ParseResultExtensions.cs(37,27): warning CS0618: 'HelpException' is obsolete: 'This is intended to facilitate refactoring during parser replacement and should not be used after that work is done.' [/cli/src/dotnet/dotnet.csproj]
         Program.cs(41,20): warning CS0618: 'HelpException' is obsolete: 'This is intended to facilitate refactoring during parser replacement and should not be used after that work is done.' [/cli/src/dotnet/dotnet.csproj]


       "/cli/build.proj" (Compile target) (1) ->
       "/cli/src/redist/redist.csproj" (Publish target) (2) ->
       "/cli/src/tool_msbuild/tool_msbuild.csproj" (default target) (5:2) ->
       (CoreCompile target) -> 
         CSC : error CS2015: '/cli/.nuget/packages/microsoft.build.runtime/15.5.179/contentFiles/any/netcoreapp1.0/MSBuild.dll' is a binary file instead of a text file [/cli/src/tool_msbuild/tool_msbuild.csproj]

    7 Warning(s)
    1 Error(s)

```

**Comment by livarcocc** [comment]
MSBuild has pushed some packages to Nuget.org after our release that are broken, we have since fixed them for 2.1.4, which is why you can't build with the 2.1.3 tag. If you checkout release/2.1 branch, it should succeed.
