### ISSUE TITLE
Cannot restore project references

### ISSUE THREAD

**Issue by mattblagden** [dotnet/cli#966]
There may be a proper/better way to reference projects that I don't know about, but the only way I can find appears to be malfunctioning right now.

In short:

* Referencing projects in sibling folders does not work without a ```global.json``` (it used to, in versions of the tools from a few days ago)
* Even with a ```global.json```, referencing a project that has project dependencies of its own throws an exception during restore.

The following steps were carried out using the latest release for OSX (installer SHA1 ```44cb2501dede4b535714cd93a011f6bb3aa61252```).

# Case 1 - Can't reference siblings without ```global.json```

In previous versions of the tools, I was able to reference sibling projects as dependencies just by naming them in ```project.json```. This no longer works.

The following example creates a library (```Lib```) and an application to depend upon it (```App```).

## Library in ```~/Case1/Lib```

After a ```dotnet new```, change the following files:

```~/Case1/Lib/project.json``` (remove emit entrypoint option):

```
{
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

```~/Case1/Lib/Program.cs``` (make a simple library):

```
namespace Lib 
{
    public class Adder
    {
        public static int Add(int a, int b)
        {
            return a + b;
        }
    }
}
```

Clean, restore and build works as expected (```rm -rf ./obj ./bin ./project.lock.json ; dotnet restore ; dotnet build```).

## App in ```~/Case1/App```

After a ```dotnet new```, change the following files:

```~/Case1/App/project.json``` (reference the "Lib" sibling folder):

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704",
        "Lib": ""
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

```~/Case1/App/Program.cs``` (invoke the lib):

```
using System;

namespace App 
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine(Lib.Adder.Add(1, 2));
        }
    }
}
```

Build fails (```rm -rf ./obj ./bin ./project.lock.json ; dotnet restore ; dotnet build```).

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for /Users/matt/Case1/App/project.json...
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
info : Committing restore...
info : Restore completed in 569ms.

Project App will be compiled because expected outputs are missing. 

Compiling App for DNXCore,Version=v5.0
/Users/matt/Case1/App/project.json(9,9): error NU1001: The dependency Lib could not be resolved.
/Users/matt/Case1/App/Program.cs(9,31): error CS0103: The name 'Lib' does not exist in the current context

Compilation failed.
    0 Warning(s)
    2 Error(s)

Time elapsed 00:00:01.2854656
```

Looking at ```~/Case1/App/project.lock.json```, I can see the ```Lib``` dependency is not being fully included; the only place it's mentioned is at the very end:

```
"projectFileDependencyGroups": {
  "": [
    "Lib ",
    "NETStandard.Library >= 1.0.0-rc2-23704"
  ],
  "DNXCore,Version=v5.0": []
}
```

## The "fix"

Adding a ```global.json``` in the parent directory (the directory that contains the ```App``` and ```Lib``` subdirectories) allows projects to reference each other again.

```~/Case1/global.json``` :

```
{
    "projects": ["./"]
}
```

Cleaning, restoring, and building ```App``` now works (```rm -rf ./obj ./bin ./project.lock.json ; dotnet restore ; dotnet build```).

```~/Case1/App/project.json``` shows proper inclusion of the ```Lib``` dependency now as well:

```
"Lib/1.0.0": {
  "type": "project",
  "framework": "DNXCore,Version=v5.0",
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-23704"
  }
}
```

# Case 2 - Can't reference projects that reference other projects

Sadly, the fix in Case 1 only works for a dependency with no dependencies of its own. Chained dependencies (e.g. ```App``` -> ```Intermediate``` -> ```Lib```) cause an exception during restore.

To keep this a bit shorter (since the actual C# doesn't seem to matter; only restoration has issues), I'll just show the JSON files:

```~/Case2/global.json``` :

```
{
    "projects": ["./"]
}
```

```~/Case2/App/project.json``` :

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704",
        "Intermediate": ""
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
``` 

```~/Case2/Intermediate/project.json``` :

```
{
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704",
        "Lib": ""
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

```~/Case2/Lib/project.json``` :

```
{
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

With this setup, restoring/building ```Lib``` succeeds, and restoring/building ```Intermediate``` succeeds, but restoring ```App``` fails with the following exception:

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for /Users/matt/Case2/App/project.json...

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Commands.RestoreCommand.GetDependencyVersionRange(LibraryDependency dependency)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.Commands.RestoreCommand.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

# Conclusion

I'm not sure if requiring a ```global.json``` was an intentional change, so Case 1 may or may not actually be an issue.

I do not have a workaround for Case 2; I am simply unable to build any parts of my codebase that have more than a single project reference in depth.

**Comment by davidfowl** [comment]
/cc @emgarten 

`global.json` shouldn't be required, if that's the case then something broke hard after we shifted to use nuget. You need to restore both projects for nuget to place them in the lock file so make sure that's happening by manually restoring both then compiling.

**Comment by mattblagden** [comment]
It's nice to hear ```global.json``` won't be needed; I liked it that way, heh.

Now that we can focus on that one case (should be able to reference siblings without a ```project.json```), here's a quick repro that just makes project ```One``` reference project ```Two``` (again, on most recent OSX):


```
mkidr One && cd $_ && dotnet new && cd ..
mkdir Two && cd $_ && dotnet new && cd ..
sed -i '' -e 's/\"dependencies\": {/\"dependencies\": { \"Two\": \"\",/' ./One/project.json
```

See dependency:
```cat ./One/project.json``` 

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": { "Two": "", 
        "NETStandard.Library": "1.0.0-rc2-23704"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

Build Two (succeeds):

```cd Two && dotnet restore && dotnet build && cd ..```

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for /Users/matt/Repro/Two/project.json...
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (osx.10.10-x64).
info : Committing restore...
info : Restore completed in 699ms.

Project Two will be compiled because expected outputs are missing. 

Compiling Two for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.5452887
``` 

Build One (fails):

```cd One && dotnet restore && dotnet build```

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for /Users/matt/Repro/One/project.json...
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (osx.10.10-x64).
info : Committing restore...
info : Restore completed in 576ms.

Project One will be compiled because expected outputs are missing. 

Compiling One for DNXCore,Version=v5.0
/Users/matt/Repro/One/project.json(7,30): error NU1001: The dependency Two could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:01.3653449
```

**Comment by emgarten** [comment]
This has been fixed in NuGet. It should make it into the CLI build soon.

https://github.com/NuGet/Home/issues/1939

**Comment by mattblagden** [comment]
Confirmed working in 1.0.1.001060. Great stuff! Thank you! :+1:

**Comment by masaeedu** [comment]
@mattblagden Is the v 1.0.1 of the dotnet CLI or of some other tool? I'm looking at the latest binaries for dotnet-cli [here](https://github.com/dotnet/cli#rtm-and-preview-2-bits) and can't see any 1.0.1 version

**Comment by mattblagden** [comment]
@masaeedu The versions mentioned in the original issue were pre-release bundle versions (this issue was from January, a fair bit of time before before release). You can rest assured the issue is fixed in any releases available today (e.g. the current 1.0 releases); my builds all follow that pattern.
