### ISSUE TITLE
Building the CLI gives a out of memory exception

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#652]
On OSX El Capitan. 

```
~/dev/cli
*** Testing stage2... ***
Publishing E2E for DNXCore,Version=v5.0/osx.10.10-x64
Compiling Microsoft.Extensions.DependencyModel for DNXCore,Version=v5.0

Unhandled Exception: OutOfMemoryException.
Copy From: /Users/dfowler/dev/cli/artifacts/tests/Microsoft.Extensions.DependencyModel.dll
       To: /Users/dfowler/dev/cli/artifacts/osx.10.10-x64/stage2/bin/
Copy From: /Users/dfowler/dev/cli/artifacts/tests/Microsoft.Extensions.DependencyModel.pdb
       To: /Users/dfowler/dev/cli/artifacts/osx.10.10-x64/stage2/bin/

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3028968

Published 0/1 projects successfully
```

**Comment by piotrpMSFT** [comment]
I'm seeing the same. This only started yesterday and only repros on el cap. Exception is getting swallowed so no idea where this is coming from...

**Comment by davidfowl** [comment]
So 2 things:
- why is the ci passing?
- can we revert the change that is causing it?

**Comment by piotrpMSFT** [comment]
CI is not on El Cap yet. Have you identified the offending PR?

**Comment by davidfowl** [comment]
F# support PR is what makes it fail

/cc @KevinRansom @enricosada

**Comment by enricosada** [comment]
I have not added an E2E test for fsharp. 

I cannot repro. No El cap locally in OS X

**Comment by brthor** [comment]
We are seeing this our VSO builds for OS X.

Relevant Error:
```
2015-12-23T09:18:53.228Z: Publishing [33mE2E[39m for [33mDNXCore,Version=v5.0[39m/[33mosx.10.10-x64[39m
2015-12-23T09:18:54.069Z: Compiling [33mMicrosoft.Extensions.DependencyModel[39m for [33mDNXCore,Version=v5.0[39m
2015-12-23T09:18:54.692Z: 
2015-12-23T09:18:54.692Z: Unhandled Exception: OutOfMemoryException.
```

This seems to have appeared with the Server GC change to CoreHost. 
PR #638 

@schellap

**Comment by schellap** [comment]
Taking a look

**Comment by schellap** [comment]
The PR #658 undoes SERVER_GC change for CLI which causes this problem.

We need to resolve #488 to enable SERVER_GC by default [OR] at least we should have a temporary solution of disabling SERVER_GC using an environment flag, so VSO can set this variable to switch off. Otherwise it is enabled. How does that sound?

https://github.com/dotnet/cli/pull/658/files

**Comment by schellap** [comment]
@davidfowl, to unblock just flip the bit.

https://github.com/dotnet/cli/blob/504e109947865d98bb87b1dec4c7d8f5daf0f8fe/src/corehost/src/main.cpp#L130

Set to "0"

**Comment by gkhanna79** [comment]
@janvorli Can you please take a look to understand why enabling Server GC would trigger OOM on OSX Elcapitan?

**Comment by kouvel** [comment]
I'll take a look at this

**Comment by schellap** [comment]
Reopening... @piotrpMSFT @sergiy-k

**Comment by davidfowl** [comment]
Finally!

**Comment by andschwa** [comment]
Noticed there is no milestone... Also just hit this, would love to compile a project on El Capitan :boat:

**Comment by gkhanna79** [comment]
This is affecting vso osxbuild

**Comment by gkhanna79** [comment]
Clicked the wrong button on phone :(

**Comment by andschwa** [comment]
Just to make it obvious (since I pieced it together from a couple linked threads):

```sh
export COREHOST_SERVER_GC=0
```

And then build happily :)

(With `ulimit -S -n 4096` being the work-around to restore without crashing; unrelated but also needed on OS X.)

**Comment by gkhanna79** [comment]
@janvorli ptal

**Comment by davidfowl** [comment]
FYI I turned it off by default for now

**Comment by gkhanna79** [comment]
@davidfowl Which PR?

**Comment by schellap** [comment]
@davidfowl please @ mention on the PR or commit message for the host, #WorldMovedUnderFeet

**Comment by piotrpMSFT** [comment]
This is fixed.
